# Generated by Django 3.1.2 on 2020-12-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20201228_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='id',
        ),
        migrations.AddField(
            model_name='product_detail',
            name='Product_id',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='is_feasibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feasibility_detail',
            name='Pattern_development_time',
            field=models.TextField(),
        ),
    ]
